# Generated by Django 5.2.1 on 2025-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='totalDonations',
            field=models.FloatField(default=0),
        ),
    ]
