# Generated by Django 5.2.1 on 2025-05-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_funding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
