# Generated by Django 5.2.3 on 2025-06-12 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_funding', '0002_extrainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
