# Generated by Django 5.2.3 on 2025-06-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_funding', '0003_projects_created_at_projects_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
